#!/bin/bash

if (($# == 0)); then
  input=/dev/stdin
else
 input=$1
fi

cat $input | while read line
do
	echo -n $line | wc -c
done | sort -n | uniq -c | sed -E "s/[^0-9]+([0-9]+)[^0-9]+([0-9]+)/\2 \1/"
